#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCDi+XTSdATfCfZX9obNll1rGdKKCN+vaxOdh3fTi1vDzSRDlxZ7597jp24FJYr14+VcauZHTmpMatmbrYAIsrTSGi/1e6GPa6zAYLOSSp53Hn5QtrAkNNodqrm9gsOJJ47vMciXutu4+8RZQFgzk0HbA60EPWLC/7c6vUJ2rg6rGCZ+jMFmyIdWq0SqOlDx6aWzBgJFKj02La4zR+esCwP4edqUBdxgPY/NS+PETf1NzYwDIFvwqj5kvngFyFUCaTZt0Vp768g8pzKAoQticaSjdx762/3vLrHN4JXtT+JRm2m4tIlO5+zNoQQ82dj4bN/Q3VXwszaz8Nl7r4aKzZv aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
write_files:
  - path: /var/www/html/db.php
    content: |
      <?php
              //database
              $servername = "3.89.222.208";
              $username = "admin";
              $password = "password";
              $dbname = "mysql";

              // Create connection
              $conn = new mysqli($servername, $username, $password, $dbname);
              // Check connection
              if ($conn->connect_error) {
                      die("Connection failed: " . $conn->connect_error);
              }

              $sql = "select Host, User from mysql.user;";
              $result = $conn->query($sql);
              while($row = $result->fetch_assoc()){
                      echo($row["Host"] . " / " . $row["User"] . "<br />");
              }
              //var_dump($result);
        ?>
  - path: /var/www/html/info.php
    content: |
      <?php

      // Show all information, defaults to INFO_ALL
      phpinfo();

      ?>
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2